# Generated by Django 3.1.5 on 2021-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0002_teammate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
