# Generated by Django 3.1.5 on 2021-03-30 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoteApp', '0003_auto_20210330_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMate',
            new_name='UserProfile',
        ),
    ]
